singleQuote: true
trailingComma: "all"
tabWidth: 4
useTabs: true
endOfLine": "lf"
bracketSpacing: true
semi: true
arrowParens: 'always'
plugins: ["@trivago/prettier-plugin-sort-imports"]
importOrderSeparation: true
importOrder: [
  "<THIRD_PARTY_MODULES>",
  "^@/(.*)$",
  "^[./]",
]
overrides:
  - files:
      - '**/*.yml'
      - '**/*.yaml'
    options:
      useTabs: false
      tabWidth: 2
  - files:
      - '**/*.md'
    options:
      useTabs: true
      tabWidth: 2
